version: "3.8"

services:
  paper-agent:
    build: .
    container_name: paper-agent
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OLLAMA_MODEL=llama3.1:8b
    command: uvicorn src.app:app --host 0.0.0.0 --port 8000
